# https://taskfile.dev

version: '3'

tasks:
  stow:
    desc: update symlinks with stow
    cmds:
      - cd symlinks/
      #- stow --restow --adopt --target ~ --verbose --no-folding */
      - touch test
      - git restore .
      - cd ..
