[tools]
# Core tools
node = "24"
python = "3.13"
go = "latest"
chezmoi = "latest"

# Dev tools
neovim = "latest"
zellij = "latest"
lazygit = "latest"
lsd = "latest"
oh-my-posh = "latest"
ripgrep = "latest"
fzf = "latest"
zoxide = "latest"
jq = "latest"
task = "latest"
"github:cli/cli" = "latest"
uv = "latest"
"pipx:neovim-remote" = "latest"
tree-sitter = "latest"
